const NUMBER_MOVIES_DESKTOP = 3
const TABLET_ITEMS_DISPLAY = 2
const MOBILE_ITEMS_DISPLAY = 2

const EMAIL_REGEX = "[a-zA-Z0-9_.]+@[a-zA-Z0-9_]+\\.[a-z]{2,}"

const MAX_SHORT_DURATION = 40

export {
  NUMBER_MOVIES_DESKTOP,
  TABLET_ITEMS_DISPLAY,
  MOBILE_ITEMS_DISPLAY,
  EMAIL_REGEX,
  MAX_SHORT_DURATION,
}