const NUMBER_MOVIES_DESKTOP = 3
const TABLET_ITEMS_DISPLAY = 2
const MOBILE_ITEMS_DISPLAY = 2

const EMAIL_REGEX = "[a-zA-Z0-9_.]+@[a-zA-Z0-9_]+\\.[a-z]{2,}"

const MAX_SHORT_DURATION = 40

const SIZE_DESKTOP = 1022
const SIZE_TABLET = 766

const SIZE_TWELVE = 12
const SIZE_EIGHT = 8
const SIZE_FIVE = 5

export {
  NUMBER_MOVIES_DESKTOP,
  TABLET_ITEMS_DISPLAY,
  MOBILE_ITEMS_DISPLAY,
  EMAIL_REGEX,
  MAX_SHORT_DURATION,
  SIZE_DESKTOP,
  SIZE_TABLET,
  SIZE_TWELVE,
  SIZE_EIGHT,
  SIZE_FIVE,
}